### ISSUE TITLE
Improvement: Improve The Pages Responsiveness in the statistics child routes

### ISSUE THREAD

**Issue by psykat1116** [psykat1116/Modern_Periodic_Table#2]
Child Pages Of Statistics are Highly Unresponsive. 
It is implemented using [react-chartjs-2](https://react-chartjs-2.js.org/)
You Can See Unresponsiveness In on of the route  **`/statistics/covalent_radius`**
You Can Go through the [react-chartjs-2](https://react-chartjs-2.js.org/) or my Codebase for better understanding.

**Comment by Vinaysohaliya** [comment]
i would like to work on this issue, can you assign me at 15 Jan

**Comment by psykat1116** [comment]
Ok, I will assign you tomorrow for this.

**Comment by psykat1116** [comment]
@Vinaysohaliya Please Confirm If you are working on this issue or not. You have no response for long time.

**Comment by Vinaysohaliya** [comment]
Right now I'm work on another issue so you can assign it to another student.

**Comment by Hrx4** [comment]
i want to give it a try

**Comment by psykat1116** [comment]
@Hrx4 Please Give Some Update

**Comment by psykat1116** [comment]
@Hrx4 Please Give Some Updates
