### ISSUE TITLE
Bug: Fix The Issue Of Overflowing Unit Boxes

### ISSUE THREAD

**Issue by psykat1116** [psykat1116/Modern_Periodic_Table#3]
In the individual elements route you can see for some of the properties has unit associated with it. But They are overflowing with each other.
It is implemented using [Headless UI](https://headlessui.com/) and I use `Listbox(Select)` from this.
You can go through the official documentation or my codebase for better understanding.

![Screenshot 2024-01-12 102031](https://github.com/psykat1116/Modern_Periodic_Table/assets/95569573/728a4eab-7640-4be3-8355-9da853f14890)

**Comment by Hrx4** [comment]
Hey @psykat1116   assign this issue to me under JWOC
