### ISSUE TITLE
Enhancement: Update The Atom Structure 2D to 3D model

### ISSUE THREAD

**Issue by psykat1116** [psykat1116/Modern_Periodic_Table#4]
Update The 2D atom structure into a 3D structure.
You can choose any library you want. But the most popular one is [three JS](https://threejs.org/).

![Screenshot 2024-01-12 103456](https://github.com/psykat1116/Modern_Periodic_Table/assets/95569573/2e0c6773-2153-42de-b03c-df37654e45b8)

**Comment by AviralSingh-code** [comment]
I would like to work on that issue under JWOC

**Comment by AviralSingh-code** [comment]
https://github.com/psykat1116/Modern_Periodic_Table/assets/72146088/524c3fc7-5555-4e49-a649-08242054106f

**Comment by AviralSingh-code** [comment]
I have also made a basic version of the hydrogen atom and we can move the atom to see the full view of the structure !! If this feels good I will implement this on all the atoms

**Comment by psykat1116** [comment]
@AviralSingh-code Ok, It is looking Excellent For Me. I am assigning you for this project.

**Comment by AviralSingh-code** [comment]
Update: I am working on this and maybe in 2-3 days I will create a PR.

**Comment by psykat1116** [comment]
Give Some Update @AviralSingh-code

**Comment by AviralSingh-code** [comment]
I have completed it and today I will create a PR !!
