### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by Pranav-Rastogi1** [psykat1116/Modern_Periodic_Table#6]

**Comment by psykat1116** [comment]
Can you describe something? @Pranav-Rastogi1

**Comment by viendimine** [comment]
Actually p-block elements are not alligned properly in vertical , so I want to fix this issue , please assign it to me.

**Comment by psykat1116** [comment]
Ok, Go For It But Please Give a Image Of That In The Comment. @Pranav-Rastogi1

**Comment by psykat1116** [comment]
@Pranav-Rastogi1 Please Give Some Update

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.

**Comment by psykat1116** [comment]
@Pranav-Rastogi1 please give update otherwise I will give it to other.

**Comment by vishal2005025** [comment]
Ok!

**Comment by vishal2005025** [comment]
sir, alignment looks fine to me so what is the Issue please elaborate.

**Comment by psykat1116** [comment]
Then Ok Ignore It.
